export const FETCHING_SETTINGS = "FETCHING_SETTINGS";
export const FETCH_SETTINGS_SUCCESS = "FETCH_SETTINGS_SUCCESS";
export const UPDATING_SETTINGS = "UPDATING_SETTINGS";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";

export const ADD_BACKUP_DATABASE = "ADD_BACKUP_DATABASE";
export const ADDING_BACKUP_DATABASE = "ADDING_BACKUP_DATABASE";
export const ADD_DATABASE_SUCCESS = "ADD_DATABASE_SUCCESS";

export const SETTINGS_ERROR = "SETTINGS_ERROR";
